# Install Pandas

In [9]:
# pip install pandas

Requirement already satisfied: pandas in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd

# Series

In [19]:
s1 = pd.Series([5, 10, 15], ['Bangkok', 'Pathum Tani', 'Nonthaburi'])

print(s1)

s1['Bangkok']

Bangkok         5
Pathum Tani    10
Nonthaburi     15
dtype: int64

5

# DataFrame

In [24]:
list = [
    [1,	'Garnt', 500, 12],
    [2, 'Beer', 400, 17],
    [3, 'Min', 350, 18]]
df = pd.DataFrame(list, columns=[ 'Key', 'Name', 'Wage', 'Hour' ])
df

   Key   Name  Wage  Hour
0    1  Garnt   500    12
1    2   Beer   400    17
2    3    Min   350    18

In [30]:
df['Salary'] = df['Wage'] * df['Hour']
df

   Key   Name  Wage  Hour  Salary
0    1  Garnt   500    12    6000
1    2   Beer   400    17    6800
2    3    Min   350    18    6300

In [36]:
df[(df['Wage'] >= 400) & (df['Hour'] < 15)]

   Key   Name  Wage  Hour
0    1  Garnt   500    12

In [34]:
df.drop('Salary', axis=1, inplace=True)
df

   Key   Name  Wage  Hour
0    1  Garnt   500    12
1    2   Beer   400    17
2    3    Min   350    18

# BMI

In [54]:
list = [
        [ 9435, "Somsri", 95, 51, 159 ]
    ,   [ 9435, "SomSak", 75, 71, 177 ]
    ,   [ 9435, "Somboon", 90, 90, 181 ]
    ,   [ 9435, "SomJai", 42, 42, 161 ]
    ]
cols = [ 'HOSPCODE', 'NAME', 'AGE', 'WEIGHT', 'HEIGHT' ]

df = pd.DataFrame(list, columns=cols)
df['BMI'] = df['WEIGHT'] / ((df['HEIGHT'] / 100) ** 2)

df[df['BMI'] > 22]

   HOSPCODE     NAME  AGE  WEIGHT  HEIGHT        BMI
1      9435   SomSak   75      71     177  22.662709
2      9435  Somboon   90      90     181  27.471689

# CSV

In [59]:
df = pd.read_csv('6606405/assets/staffs.csv')
df

   รหัส    ชื่อ  ค่าจ้าง  ชั่วโมง
0     1   กานต์      500       12
1     2  เบียร์      400       17
2     3     มิน      350       18

In [60]:
df['รายได้'] = df["ค่าจ้าง"] * df["ชั่วโมง"]
df.to_csv('6606405/assets/staffs_with_payment.csv', index=False, encoding='utf-8-sig')

In [68]:
#pip install xlrd openpyxl

Requirement already satisfied: xlrd in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (2.0.2)
Requirement already satisfied: openpyxl in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\it\downloads\wpy64-31241\python-3.12.4.amd64\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [71]:
df = pd.read_excel('6606405/assets/staffs_payment.xlsx', sheet_name='Sheet1')
df

   รหัส    ชื่อ  ค่าจ้าง  ชั่วโมง  รายได้
0     1   กานต์      500       12    6000
1     2  เบียร์      400       17    6800
2     3     มิน      350       18    6300